### PR TITLE
Containerising Garud & All its dependencies

### PR DESCRIPTION
**Pull request by frost19k**
Containerisation simplifies the installation process for the user & allows maintainers to control the installation environment.
In the future, workflows can be created to automatically push pre-built images to Docker Hub.

As it stands, the current image is 810MB in size.

### CODE REVIEW

**Review by R0X4R — CHANGES_REQUESTED** [review]
Hi @frost19k,

Thanks for taking time out to contribute to **Garud**. I have some questions regarding the installation part. Some tools like `subzy` are no longer needed in the tool, also the installation process of `amass` may throw some errors can you please recheck the installation part. I'm a bit busy so I won't be able to check the commits manually on my system.

Thanks again,
R0X4R

**Comment by frost19k** [comment]
I'll remove subzy & I have verified amass works without error. As do all the other tools. 
The only thing I didn't verify is notify.

Although, aquatone's `-chrome-path` needs to be `$CHROME_BIN` inside the container. 
I forgot to add that change before making the commit. My bad.

**Comment by R0X4R** [comment]
Hii @frost19k,

Have you checked all these commits. Is it working fine or you have encountered any error?

**Comment by frost19k** [comment]
I have built the latest commit on two separate machines with a clean Buildkit cache. Both builds succeeded.
I have manually verified that the requisite tools exist in `/usr/local/bin` & that the expected directory tree in `~/` is correct & `gf`'s patterns are properly copied to `/root/.gf` (`.gf` cannot be moved to `/Garud`)

Changing `HOME` to `/Garud` is more an aesthetic change IMHO. It looks nicer when `.config` is mounted to `/Garud` than `/root`

Having said all this - there are a lot of moving parts to Garud & it is possible that I may have missed something. Although - I wanna assure you that I tested extensively (issue #35, for e.g.) & you can assign any future Docker related issues to me.

**Comment by R0X4R** [comment]
Hii @frost19k,

Thank you for your time and contribution. I'm approving this pr and linking this pr with your issue. Also can you please send me your Twitter id.

Thanks and regards,
R0X4R

**Comment by frost19k** [comment]
Hey, thanks for accepting my PR. 
This is the first time I've had a PR accepted! :-D

I have plans to further develop the container in such a way that the User doesn't have to configure Namespaces & I'm also looking into workflows to automate publishing the container to Docker Hub. Then users can simply `docker pull` & `docker run`!

My twitter is @hoodlytwokeys - but I'm not at all active on Social Media! :-P

**Comment by R0X4R** [comment]
Thank you @frost19k, for making **Garud** better. If you can make Garud into DockerHub container it would be very helpful. Also wishes you all the best for the future :)

Your contribution is not listed in [`https://github.com/R0X4R/Garud/blob/master/.github/contributors.md`](https://github.com/R0X4R/Garud/blob/master/.github/contributors.md)
Also wrote a tweet about this [`https://twitter.com/R0X4R/status/1468227278576435206`](https://twitter.com/R0X4R/status/1468227278576435206)

Thanks again!

**Pull request merged**
